### ISSUE TITLE
Info from Web/reddit doesn´t show up

### ISSUE THREAD

**Issue by danieldeut** [Melvin-Abraham/Google-Assistant-Unofficial-Desktop-Client#453] opened 2021-07-19 12:13 UTC
I play League of Legends and want to know Azir counters, so I asked for it.

What i did
1. Open app
2. Type in "azir counters"
3. Saw this: https://prntscr.com/1d2qgey

Notebook Lenovo Legion 5 with AMD and RTX 3060
 - OS: Win10
 - Version 1.0.0-rc.1

**Comment by sumeshir26** [comment] 2021-07-20 05:02
Hi @danieldeut,
This used to work, but then the Google Assistant SDK changed the response to "Here is what I found"/"Here is a result from YouTube" which tricks the app into thinking that it is a text result.
To fix this, nothing can be changed from the app's end.
(Duplicate of #41, #38, #53, and #131)

**Comment by Melvin-Abraham** [comment] 2021-07-22 17:57
This will possibly be worked on after the release of next version

**Comment by Melvin-Abraham** [comment] 2021-07-22 17:57
_Closing as duplicate_

**Closed by Melvin-Abraham** 2021-07-22 17:57 UTC
Labels: duplicate
