### ISSUE TITLE
Network connect fails if I turn on "Enable microphone on application startup"

### ISSUE THREAD

**Issue by defaultkavy** [Melvin-Abraham/Google-Assistant-Unofficial-Desktop-Client#314] opened 2021-04-17 07:34 UTC
My network have no problem, it just fail to connect when I turn on this setting. If I turn it off then the network back to normal again.

**Comment by defaultkavy** [comment] 2021-04-17 07:44
I just found the network problem is activated by every time I turn on mic.

**Comment by coder-lg** [comment] 2021-04-18 03:51
This is a common error to some people. If you want this on, you might have to build it yourself. I even had an issue on this. #185 it is.

**Comment by Melvin-Abraham** [comment] 2021-04-18 15:22
@defaultkavy Seems like a duplicate of #39. Based on the issue _(that I assume based on the title)_, this isn't a network problem and only occurs when no token file is found or saved. This issue has been fixed within the source tree but not released yet. If you think this is a different issue, please provide more details.

**Comment by Melvin-Abraham** [comment] 2021-04-18 15:22
_Closing as duplicate_

**Closed by Melvin-Abraham** 2021-04-18 15:22 UTC
Labels: duplicate, 🐛 bug
