### ISSUE TITLE
Bug: not showing search results, just the title

### ISSUE THREAD

**Issue by ntaraujo** [Melvin-Abraham/Google-Assistant-Unofficial-Desktop-Client#401] opened 2021-05-28 01:34 UTC
When making any search this is what happens:

![image](https://user-images.githubusercontent.com/66187211/119915235-73fd8380-bf38-11eb-92e8-50360dd66c11.png)

![image](https://user-images.githubusercontent.com/66187211/119915375-c0e15a00-bf38-11eb-8143-fa3866c2b4b5.png)

Maths, questions for the A.I., asks for definitions and some others work as expected
![image](https://user-images.githubusercontent.com/66187211/119916277-9d1f1380-bf3a-11eb-9b0c-a005e6f242a9.png)
![image](https://user-images.githubusercontent.com/66187211/119916520-0e5ec680-bf3b-11eb-965f-a285ec105398.png)
![image](https://user-images.githubusercontent.com/66187211/119916301-aa3c0280-bf3a-11eb-80a3-00b1685a6934.png)

I'm on Pop_OS! 20.04 and version 1.0.0-rc.2, installed directly from the snap store

Thanks in advance

**Comment by sumeshir26** [comment] 2021-05-28 13:32
@ntaraujo This is a problem with the Google Assistant SDK and nothing can be done for this from the app's end currently.
(Duplicate of #41, #38, #53, and #131)

**Comment by Melvin-Abraham** [comment] 2021-05-28 15:29
Any updates regarding this could be tracked in the above issues.
_Closing as duplicate_

**Closed by Melvin-Abraham** 2021-05-28 15:29 UTC
Labels: duplicate, 🐛 bug
