### ISSUE TITLE
google assistant using mic in background 24x7

### ISSUE THREAD

**Issue by Netherquark** [Melvin-Abraham/Google-Assistant-Unofficial-Desktop-Client#214] opened 2021-03-05 06:33 UTC
**Is your feature request related to a problem? Please describe.**
==> I've kept autostart with windows on. so, it starts up the assistant in the background every time and shows that it is using the mic. this is concerning in regards to privacy.

**Describe the solution you'd like**
==> ideally it shouldn't be using the mic unless I'm using the mic, so please fix that.

**Additional context**
![image](https://user-images.githubusercontent.com/65618735/110076000-c13ede80-7da9-11eb-83f6-6e3b9be1582d.png)

**Comment by Melvin-Abraham** [comment] 2021-03-07 07:40
Duplicate of #30

This issue has already been reported and has been fixed. For bug details, refer https://github.com/Melvin-Abraham/Google-Assistant-Unofficial-Desktop-Client/issues/30#issuecomment-718846607

The fix will be available in the next release of this app. Till then if you want to test it, you can clone this repo and run it locally (see [How to build?](https://github.com/Melvin-Abraham/Google-Assistant-Unofficial-Desktop-Client#how-to-build)).

**Comment by Melvin-Abraham** [comment] 2021-03-07 07:40
_Closing as duplicate_

**Closed by Melvin-Abraham** 2021-03-07 07:40 UTC
Labels: duplicate, 🐛 bug
