### ISSUE TITLE
Failed to start assistant

### ISSUE THREAD

**Issue by Goyoopp** [Melvin-Abraham/Google-Assistant-Unofficial-Desktop-Client#258] opened 2021-03-28 10:18 UTC
Error: Getting metadata from plugin failed with error: invalid_grant

**Comment by Melvin-Abraham** [comment] 2021-03-28 10:23
This is a duplicate of #58 and many others. Please refer to [this FAQ section](https://github.com/Melvin-Abraham/Google-Assistant-Unofficial-Desktop-Client/wiki/Frequently-Asked-Questions-(FAQ)#how-do-i-fix-invalid_grant-error).

**Comment by Melvin-Abraham** [comment] 2021-03-28 10:23
_Closing as duplicate_

**Closed by Melvin-Abraham** 2021-03-28 10:23 UTC
Labels: duplicate, 🐛 bug
