### ISSUE TITLE
[💡 Feature Request]: Switching from Snap Store to Flatpak?

### ISSUE THREAD

**Issue by LinuxSnapshot** [Melvin-Abraham/Google-Assistant-Unofficial-Desktop-Client#610] opened 2022-01-01 03:45 UTC
### What's your solution or idea?

Please switch to Flatpak on Snap Store or upload to Flatpak as well.

1. Snap Store's client (snapd) is GPLv3, but the server is proprietary software.

2. For Linux distributions that do not have snapd pre-installed, such as Linux Mint, you must manually install snapd. This process makes users uncomfortable.

I think Flatpak is better than Snap Store.

### Alternatives Considered

Snap Store >> Flatpak

### App Version

Built from source

### Pre-submission Checklist

- [X] I have checked [the issue tracker](https://github.com/Melvin-Abraham/Google-Assistant-Unofficial-Desktop-Client/issues?q=is%3Aissue+label%3A%22%E2%9C%A8+enhancement%22+) and didn't find any duplicate issue
- [X] This issue only covers one particular feature request

**Comment by Melvin-Abraham** [comment] 2022-01-02 06:19
Since the electron builder recently received support for flatpak builds, it might be added in new releases later...

**Comment by Melvin-Abraham** [comment] 2022-01-02 06:19
Duplicate of #87

**Comment by Melvin-Abraham** [comment] 2022-01-02 06:21
_Closing as duplicate_

You may track the progress for this in the above-mentioned issue

**Closed by Melvin-Abraham** 2022-01-02 06:21 UTC
Labels: duplicate, ✨ enhancement
