### ISSUE TITLE
Some text no show

### ISSUE THREAD

**Issue by thegamerx1** [Melvin-Abraham/Google-Assistant-Unofficial-Desktop-Client#411] opened 2021-05-29 21:31 UTC
**Describe the bug**
Text shows on real assistant not fake one

**To Reproduce**
1. type how to mcode in "ask me anything..." bar
2. press enter
3. wait
4. process with brain
5. think about results
6. no text

**Expected behavior**
i expect text

**Screenshots**
![image](https://user-images.githubusercontent.com/34986564/120084930-97f5cc00-c0d4-11eb-895a-e83c162c87f3.png)
![image](https://user-images.githubusercontent.com/34986564/120085098-9bd61e00-c0d5-11eb-8791-f7aaf56bd815.png)

**Desktop (please complete the following information):**
 - OS: binbows 10 20h2
 - Version 1.0.0-rc.2

**Additional context**
no

**Comment by sumeshir26** [comment] 2021-06-01 13:35
@thegamerx1 This is a problem with the Google Assistant SDK and nothing can be done for this from the app's end currently.
(Duplicate of #41, #38, #53, and #131)

**Comment by obed9057** [comment] 2021-06-01 13:54
i have the same issue I just ignore it sometimes like sometimes it says it found something on the web but does not show me the text nor picture from Wikipedia so probably a problem with the google services

**Comment by obed9057** [comment] 2021-06-01 13:56
> **Describe the bug**
> Text shows on real assistant not fake one
> 
> **To Reproduce**
> Steps to reproduce the behavior:
> 
> 1. type how to mcode in "ask me anything..." bar
> 2. press enter
> 3. wait
> 4. process with brain
> 5. think about results
> 6. no text
> 
> **Expected behavior**
> i expect text
> 
> **Screenshots**
> ![image](https://user-images.githubusercontent.com/34986564/120084930-97f5cc00-c0d4-11eb-895a-e83c162c87f3.png)
> ![image](https://user-images.githubusercontent.com/34986564/120085098-9bd61e00-c0d5-11eb-8791-f7aaf56bd815.png)
> 
> **Desktop (please complete the following information):**
> 
> * OS: binbows 10 20h2
> * Version 1.0.0-rc.2
> 
> **Additional context**
> no

its Windows 10 no windows and have you tried getting the 21H2 insider update?

**Comment by obed9057** [comment] 2021-06-01 13:57
not bindows*

**Closed** 2021-07-17 00:06 UTC
Labels: 🐛 bug
