### ISSUE TITLE
[💡 Feature Request]: 

### ISSUE THREAD

**Issue by JonibekErgashev** [Melvin-Abraham/Google-Assistant-Unofficial-Desktop-Client#601] opened 2021-12-08 18:16 UTC
### What's the Problem?

Google assistant can find thing which i want not as mobil google assistant. He only find wikipedia informations. 

### What's your solution or idea?

Please slove this

### Alternatives Considered

I think, you need connect google assistant with google

### App Version

v1.0.0-rc.2

### Pre-submission Checklist

- [X] I have checked [the issue tracker](https://github.com/Melvin-Abraham/Google-Assistant-Unofficial-Desktop-Client/issues?q=is%3Aissue+label%3A%22%E2%9C%A8+enhancement%22+) and didn't find any duplicate issue
- [X] This issue only covers one particular feature request

**Comment by sumeshir26** [comment] 2021-12-09 02:47
@JonibekErgashev Due to the unofficial nature of the client, it uses some "Hackish" workarounds using the Google Assistant SDK. Therefore, not all features in the mobile/ChromeOS app can be supported...

**Comment by Melvin-Abraham** [comment] 2021-12-11 04:11
Duplicate of #41.

You may track any changes regarding this issue there...

**Comment by Melvin-Abraham** [comment] 2021-12-11 04:12
_Closing as duplicate_

**Closed by Melvin-Abraham** 2021-12-11 04:12 UTC
Labels: duplicate, ✨ enhancement
