### ISSUE TITLE
Microphone is permanently in use

### ISSUE THREAD

**Issue by LinqLover** [Melvin-Abraham/Google-Assistant-Unofficial-Desktop-Client#173] opened 2021-02-22 21:13 UTC
Even when the assistant window is not open, it permanently accesses the microphone (I discovered this using [OnAirSync](/LinqLover/OnAirSync)). This is not only questionable with regard to privacy (even though I tend to trust open-source projects) but also creates misleading displays in other applications (Windows keeps showing the "Your mic is in use" icon in the tray, OnAirSync is confused, etc.) and probably might cause conflicts with other applications interested in using the microphone.

**Expected behavior**
The microphone should only be in use when the assistant is actually listening to me - unless #111 (wake word) is implemented.

**Desktop (please complete the following information):**
 - OS: Win 2004
 - Version: v1.0.0-rc.2

**Comment by Melvin-Abraham** [comment] 2021-02-23 08:42
@LinqLover Duplicate of #30. This issue has already been addressed and fixed within the source just not released yet.
_Closing as duplicate_

**Closed by Melvin-Abraham** 2021-02-23 08:42 UTC
Labels: duplicate
