### ISSUE TITLE
JavaScript timeout error

### ISSUE THREAD

**Issue by LillyYaGirl** [Melvin-Abraham/Google-Assistant-Unofficial-Desktop-Client#123] opened 2021-02-13 18:54 UTC
When I download and install the pre compiled .EXE installer for my Windows 10 desktop, and then try to open it, the following error is presented. This occurs even when running the software as administrator and after a Java update.

![javascript done messed up](https://user-images.githubusercontent.com/79021122/107858577-e8d20500-6e02-11eb-90dc-6f774e6032e0.PNG)

**Comment by thijshofkes14** [comment] 2021-02-13 20:29
Same!!

**Comment by leonardooleg** [comment] 2021-02-13 22:24
Same!!

**Comment by srivmanu** [comment] 2021-02-14 05:06
Please see #80

**Comment by Melvin-Abraham** [comment] 2021-02-14 05:08
Duplicate of #39 and #80.

> Seems like this issue is similar to #35. This is a bug which occurs due to passing a floating-point number to the `setPosition()` function, which is calculated based on your screen size. Thus, the only way to get around it for the time-being is to clone this repo (via `git clone`) and build it yourself (see [How to build](https://github.com/Melvin-Abraham/Google-Assistant-Unofficial-Desktop-Client#how-to-build)) since it has been fixed within the source but not released yet.

You can learn more about this bug [here](https://github.com/Melvin-Abraham/Google-Assistant-Unofficial-Desktop-Client/issues/35#issuecomment-726725640).

**Comment by thijshofkes14** [comment] 2021-02-14 08:33
I just could'nt get the npm build to work, kept spamming me with errors.. So i'll just have to wait for the next release then.. :/

**Comment by Melvin-Abraham** [comment] 2021-02-14 09:51
@thijshofkes14 If you are on Windows, you might need to install **MS Visual Studio C++ Runtime** and other build tools for building native modules that the project depends upon...

To install Windows Build Tools, run the following command in Powershell as Administrator:

```
npm install --global windows-build-tools
```

OR, if you are using Yarn

```
yarn global add windows-build-tools
```

Once installed, try building the application once again

**Comment by thijshofkes14** [comment] 2021-02-14 12:00
Got it working. Thank you very much! Nice application.

**Closed** 2021-02-15 17:54 UTC
Labels: duplicate
