### ISSUE TITLE
Windows says Google Assitant is using the mic even when closed to tray

### ISSUE THREAD

**Issue by OscarPalafox** [Melvin-Abraham/Google-Assistant-Unofficial-Desktop-Client#133] opened 2021-02-14 15:32 UTC
**Describe the bug**
When the app is closed to tray, Windows considers the mic is still in use by the app. Since I am using Bluetooth headphones, this makes the app unusable (different playback devices are used when only sound is sent to the Bluetooth device or when the mic of the Bluetooth headphones are used) as I am unable to use the "good" sound device and I am stuck with using the poorer sound.
I have tried to disable all the options regarding the mic (`Enable microphone on Continous Conversation`, `Enable microphone on application startup`, `Enable 'ping' feedback sound for microphone`) and I have configured the `Hotkey Behaviour` to only `Launch App`, but even though they are all disabled the app is still able to use the mic.

**To Reproduce**
1. Connect bluetooth headphones that appear as several playback devices (Stereo and Hands-Free AG Audio), this happens with the Bose QC 35II, Sony WH-1000XM4 and WH-1000XM3 and probably any headphones that have a mic and are connected through Bluetooth
2. Open the Google Assitant app
3. You are now unable to hear sound with the Stereo device and are stuck to using the Hands-Free AG Audio device since Windows considers the app is using the mic.

**Expected behavior**
Windows should not consider that the mic is still in use after the app is closed to the tray. Ideally, the app would work like Discord and other similar apps where the sound of the app is momentarily sent through a set device so that a user that has Bluetooth headphones does not need to change devices to hear the Assistant's response. A perhaps "easier" solution would be to allow the user to choose the device through which the sound is sent and received, i.e. the input and output device.

**Screenshots**
N/A

**Desktop (please complete the following information):**
 - OS: Windows 10 Home Build 19042.804
 - Version 1.0.0-rc.2

**Additional context**
A perfectly valid fix to this would be to simply allow the user to choose the input and output device.
Thanks for the app, other than the issue mentioned it works great and was super easy to set up.

**Comment by Melvin-Abraham** [comment] 2021-02-14 15:51
@OscarPalafox When you launch the app, it checks to see if the microphone is accessible on start itself by turning on the microphone. That is the reason you see the microphone as active even though you are just launching the app.

Duplicate of #30. This issue has already been reported and has been fixed within the source. For bug details, refer https://github.com/Melvin-Abraham/Google-Assistant-Unofficial-Desktop-Client/issues/30#issuecomment-718846607

The fix will be available in the next release of this app. Till then if you want to test it, you can clone this repo and run it locally (see [How to build?](https://github.com/Melvin-Abraham/Google-Assistant-Unofficial-Desktop-Client#how-to-build)).

**PS:** If you are temporarily having issues due to this bug and do not want to build it, I would recommend you to quit the app instead of just closing it _(you can disable **Settings** > **Application** > **Always Close to Tray**)_ when you are not using it until the next version is released.

**Comment by OscarPalafox** [comment] 2021-02-14 15:58
Thanks for the quick reply! I didn't think of checking the closed issues. I'll use the setting to avoid it closing to the tray in the meantime. @Melvin-Abraham, do you know if it's possible to implement the feature on choosing the output device and outputting sound to that while the app is open ? I could open a separate issue to make things easier.

**Comment by Melvin-Abraham** [comment] 2021-02-14 15:59
> A perhaps "easier" solution would be to allow the user to choose the device through which the sound is sent and received, i.e. the input and output device.

This feature has been implemented as per the issue #22.

**Comment by Melvin-Abraham** [comment] 2021-02-17 07:39
_Closing as resolved_

**Closed by Melvin-Abraham** 2021-02-17 07:39 UTC
Labels: duplicate
