### ISSUE TITLE
I asked it to show the top results of something, it just replied "Here are the top results" and nothing comes after it everything is blank at least it must show some of the results and redirect us to google. Pls help

### ISSUE THREAD

**Issue by Anshum-Bhargav** [Melvin-Abraham/Google-Assistant-Unofficial-Desktop-Client#278] opened 2021-04-07 17:02 UTC
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. Windows 10 Build 1909]
 - Version [e.g. 1.0.0-rc.1]

**Additional context**

**Comment by Melvin-Abraham** [comment] 2021-04-08 12:41
Duplicate of #41

**Comment by Melvin-Abraham** [comment] 2021-04-08 12:42
_Closing as duplicate_

**Closed by Melvin-Abraham** 2021-04-08 12:42 UTC
Labels: duplicate, 🐛 bug
