### ISSUE TITLE
Can't get image results what so ever!!

### ISSUE THREAD

**Issue by Icy-CooL** [Melvin-Abraham/Google-Assistant-Unofficial-Desktop-Client#262] opened 2021-04-03 16:38 UTC
![image](https://user-images.githubusercontent.com/81872002/113484999-fcc3ea00-94c8-11eb-8ddc-d7105fb1bf66.png)
I tried it several times with different keywords but its not functional

Hope you consider this 😄

**Comment by Melvin-Abraham** [comment] 2021-04-04 04:24
Duplicate of #38 and #41.

**Comment by Melvin-Abraham** [comment] 2021-04-04 04:24
_Closing as duplicate_

**Closed by Melvin-Abraham** 2021-04-04 04:24 UTC
Labels: duplicate
