### ISSUE TITLE
I can't see pictutures in Google Assistant

### ISSUE THREAD

**Issue by Seewak342** [Melvin-Abraham/Google-Assistant-Unofficial-Desktop-Client#172] opened 2021-02-22 15:29 UTC
**Describe the bug**
The pictures when I ask in google assistant are not there

**To Reproduce**

"Picture of cats, dogs etc."

**Expected behavior**
Picture Of dogs, cats etc

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 10 Build 2004
 - Version 1.0.0-rc.2

**Additional context**

**Comment by esau-morais** [comment] 2021-02-22 15:40
Duplicate of #41

**Comment by Seewak342** [comment] 2021-02-23 00:34
How to fix the bug?

**Comment by esau-morais** [comment] 2021-02-23 08:13
Please see that the maintainer still [working](https://github.com/Melvin-Abraham/Google-Assistant-Unofficial-Desktop-Client/issues/38#issuecomment-731158481) on this

**Comment by esau-morais** [comment] 2021-03-11 11:48
I recommend closing this issue, once it's duplicated and watch the discussion in the link above

**Closed** 2021-03-14 13:55 UTC
