### ISSUE TITLE
Error: Getting metadata from plugin failed with error: invalid_grant

### ISSUE THREAD

**Issue by WatchTheory** [Melvin-Abraham/Google-Assistant-Unofficial-Desktop-Client#179] opened 2021-02-23 18:18 UTC
When opening Google assistant, and when trying something or pressing the microphone, I get this error " __Error: Getting metadata from plugin failed with error: invalid_grant_". Its says I am offline when in fact I am not, I am fully able to access the internet.  I am not sure if it has something to do with the my network.

![Proof 2](https://user-images.githubusercontent.com/50931847/108888521-30aa1680-75d1-11eb-8b51-bcd4db931702.PNG)
![bug](https://user-images.githubusercontent.com/50931847/108888102-ab266680-75d0-11eb-8be7-9773c5693d3d.PNG)

**Comment by esau-morais** [comment] 2021-02-23 18:49
Please this section on the [Frequently Asked Questions (FAQ)](https://github.com/Melvin-Abraham/Google-Assistant-Unofficial-Desktop-Client/wiki/Frequently-Asked-Questions-(FAQ)#how-do-i-fix-invalid_grant-error)

**Comment by esau-morais** [comment] 2021-02-23 18:55
Duplicate of #58, plus another 5 issues similar to this

**Comment by WatchTheory** [comment] 2021-02-23 19:07
@esau-morais  Thanks

**Closed** 2021-02-23 19:08 UTC
