### ISSUE TITLE
[💡 Feature Request]: 

### ISSUE THREAD

**Issue by SkittleChaan** [Melvin-Abraham/Google-Assistant-Unofficial-Desktop-Client#779] opened 2022-09-25 05:06 UTC
### What's the Problem?

When I ask google assistant to open a app it will say 
<img width="744" alt="image" src="https://user-images.githubusercontent.com/114326377/192129145-c905cd43-62d2-47bb-a178-34905f2b2347.png">

### What's your solution or idea?

So I hope Google Assistant Windows allow to open windows apps that will be cool.

### Alternatives Considered

-

### App Version

v1.0.0-rc.1

### OS Version

Windows 11(OS Build 22622.290)

### Additional context

-

### Pre-submission Checklist

- [X] I have checked [the issue tracker](https://github.com/Melvin-Abraham/Google-Assistant-Unofficial-Desktop-Client/issues?q=is%3Aissue+label%3A%22%E2%9C%A8+enhancement%22+) and didn't find any duplicate issue
- [X] This issue only covers one particular feature request

**Comment by SkittleChaan** [comment] 2022-09-25 05:08
So Its my computer problem or the app doesn't support that

**Comment by sumeshir26** [comment] 2022-09-25 13:27
The app dosent support that. It is on the roadmap tho

**Comment by Melvin-Abraham** [comment] 2022-10-08 14:04
Duplicate of #554

**Comment by Melvin-Abraham** [comment] 2022-10-08 14:04
_Closing as duplicate_

**Closed by Melvin-Abraham** 2022-10-08 14:04 UTC
Labels: 🐛 bug, ✨ enhancement
