### ISSUE TITLE
Ability to change hotkey

### ISSUE THREAD

**Issue by CorvetteCole** [Melvin-Abraham/Google-Assistant-Unofficial-Desktop-Client#42] opened 2020-11-29 02:11 UTC
I would simply love to be able to change the hotkey to whatever I want. That is all, could not see an option for that. Thank you

**Comment by Melvin-Abraham** [comment] 2020-11-30 05:03
_Duplicate of #24_

Any further updates will be posted there.

**Closed** 2020-12-12 07:24 UTC
Labels: duplicate
