### ISSUE TITLE
assitant not showing any photos or google search results (like websites)

### ISSUE THREAD

**Issue by Beyonder123** [Melvin-Abraham/Google-Assistant-Unofficial-Desktop-Client#430] opened 2021-06-20 05:05 UTC
### **assistant is not showing any photos or search results.. for eg; when asked "show photos of Iceland'... it is returning the result but not showing any photos or websites**

show results of the search (**including pics and websites**)

 - OS: [ Windows 10 Build 19042.1052]
 - Version [20H2]

![assistant problem](https://user-images.githubusercontent.com/77671233/122662698-a6ef0c00-d1b2-11eb-8117-f637cb6ff7af.PNG)

**Comment by sumeshir26** [comment] 2021-06-20 21:37
Hi @Beyonder123,
This used to work, but then the Google Assistant SDK changed the response to "Here is what I found"/"Here is a result from YouTube" which tricks the app into thinking that it is a text result.
To fix this, nothing can be changed from the app's end.
(Duplicate of #41, #38, #53, and #131)

**Closed** 2024-03-16 08:07 UTC
Labels: 🐛 bug
