### ISSUE TITLE
Timeout error after opening assistant

### ISSUE THREAD

**Issue by Lambada10** [Melvin-Abraham/Google-Assistant-Unofficial-Desktop-Client#170] opened 2021-02-22 11:42 UTC
**Describe the bug**
So I followed the documentation and set everything up in google cloud. Then I installed Google assistant app but it throws a timeout error. I tried reinstalling but it didn't help.

**To Reproduce**
Open assistant app

**Expected behaviour**
Assistant opens

**Screenshots**
![image](https://user-images.githubusercontent.com/62511588/108703779-5ec52300-750b-11eb-844d-76feec985f9d.png)

**Desktop (please complete the following information):**
 - OS: Windows 10 Build 20H2 Insider Beta 19042.804
 - Version 1.0.0-rc.2

**Comment by esau-morais** [comment] 2021-02-22 11:49
Duplicate of #39 and #80.

> Seems like this issue is similar to #35. This is a bug which occurs due to passing a floating-point number to the setPosition() function, which is calculated based on your screen size. Thus, the only way to get around it for the time-being is to clone this repo (via git clone) and build it yourself (see How to build) since it has been fixed within the source but not released yet.

**Comment by Melvin-Abraham** [comment] 2021-02-22 13:09
_Closing as Duplicate_

**Closed by Melvin-Abraham** 2021-02-22 13:09 UTC
Labels: duplicate

**Comment by Lambada10** [comment] 2021-02-22 13:53
I built it but I can't do anything in that
I cant go to settings to set API key or anything
Check video
![video](https://streamable.com/x0eyk2)

**Comment by Lambada10** [comment] 2021-02-22 13:54
> Duplicate of #39 and #80.
> 
> > Seems like this issue is similar to #35. This is a bug which occurs due to passing a floating-point number to the setPosition() function, which is calculated based on your screen size. Thus, the only way to get around it for the time-being is to clone this repo (via git clone) and build it yourself (see How to build) since it has been fixed within the source but not released yet.

I built it but I can't do anything in that
I cant go to settings to set API key or anything
Check video
https://streamable.com/x0eyk2

**Comment by Lambada10** [comment] 2021-02-22 14:08
I built it but I can't do anything in that
I cant go to settings to set API key or anything
Check video
https://streamable.com/2txl5l



> Duplicate of #39 and #80.
> 
> > Seems like this issue is similar to #35. This is a bug which occurs due to passing a floating-point number to the setPosition() function, which is calculated based on your screen size. Thus, the only way to get around it for the time-being is to clone this repo (via git clone) and build it yourself (see How to build) since it has been fixed within the source but not released yet.

**Comment by Lambada10** [comment] 2021-02-22 14:26
https://user-images.githubusercontent.com/62511588/108721418-43194700-7522-11eb-84a3-a823f7b36c65.mp4

**Comment by Lambada10** [comment] 2021-02-23 07:54
I can send console errors
```
Uncaught Error: Failed to load C:\Users\user\AppData\Local\Programs\Google Assistant\resources\app.asar\node_modules\grpc\src\node\extension_binary\electron-v9.3-win32-x64-unknown\grpc_node.node. Cannot find module 'C:\Users\user\AppData\Local\Programs\Google Assistant\resources\app.asar\node_modules\grpc\src\node\extension_binary\electron-v9.3-win32-x64-unknown\grpc_node.node'
Require stack:
- C:\Users\user\AppData\Local\Programs\Google Assistant\resources\app.asar\node_modules\grpc\src\grpc_extension.js
- C:\Users\user\AppData\Local\Programs\Google Assistant\resources\app.asar\node_modules\grpc\src\client_interceptors.js
- C:\Users\user\AppData\Local\Programs\Google Assistant\resources\app.asar\node_modules\grpc\src\client.js
- C:\Users\user\AppData\Local\Programs\Google Assistant\resources\app.asar\node_modules\grpc\index.js
- C:\Users\user\AppData\Local\Programs\Google Assistant\resources\app.asar\node_modules\google-assistant\components\assistant.js
- C:\Users\user\AppData\Local\Programs\Google Assistant\resources\app.asar\node_modules\google-assistant\index.js
- C:\Users\user\AppData\Local\Programs\Google Assistant\resources\app.asar\app\src\index.html
    at Module._resolveFilename (internal/modules/cjs/loader.js:797)
    at Function.i._resolveFilename (electron/js2c/renderer_init.js:43)
    at Module._load (internal/modules/cjs/loader.js:690)
    at Function.Module._load (electron/js2c/asar.js:769)
    at Module.require (internal/modules/cjs/loader.js:852)
    at require (internal/modules/cjs/helpers.js:74)
    at Object.<anonymous> (C:\Users\user\AppData\Local\Programs\Google Assistant\resources\app.asar\node_modules\grpc\src\grpc_extension.js:32)
    at Object.<anonymous> (C:\Users\user\AppData\Local\Programs\Google Assistant\resources\app.asar\node_modules\grpc\src\grpc_extension.js:64)
    at Module._compile (internal/modules/cjs/loader.js:967)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1004)
main.js:3958 Uncaught ReferenceError: Cannot access 'mic' before initialization
    at _stopAudioAndMic (main.js:3958)
    at HTMLImageElement.close_btn.onclick (main.js:11)
    ```

**Comment by Melvin-Abraham** [comment] 2021-02-23 08:35
@Lambada10 Seems like you did not install the dependencies after cloning this repo. Just go to the directory (which you cloned using `git clone`) and run the command `npm install` inside the directory. If you don't have the Windows Build Tools installed on your system, the build would fail. So, to resolve that you can run the following command before installing any dependencies:

Start PowerShell as Administrator and run:

```
npm install --global windows-build-tools
```

Or, if you are using Yarn:

```
yarn global add windows-build-tools
```

**Comment by Lambada10** [comment] 2021-02-23 09:55
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! g-assist@1.0.0-rc.2 postinstall: `electron-builder install-app-deps`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the g-assist@1.0.0-rc.2 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\user\AppData\Roaming\npm-cache\_logs\2021-02-23T09_54_06_308Z-debug.log
[2021-02-23T09_54_06_308Z-debug.log](https://github.com/Melvin-Abraham/Google-Assistant-Unofficial-Desktop-Client/files/6028078/2021-02-23T09_54_06_308Z-debug.log)

**Comment by Lambada10** [comment] 2021-02-23 10:10
Ok it's working now. Thanks
