### ISSUE TITLE
Add Option to Explicitly Specify Microphone

### ISSUE THREAD

**Issue by JakeCover** [Melvin-Abraham/Google-Assistant-Unofficial-Desktop-Client#89] opened 2021-02-12 04:52 UTC
**Is your feature request related to a problem? Please describe.**
Because of various reasons, the default microphone is not always the best choice, and so it would be useful to explicitly set the microphone for assistant to use

**Describe the solution you'd like**
A settings field to pick the microphone to use

**Describe alternatives you've considered**
This normally isn't an issue, but SteamVR often has unreliable effects on the default audio device, meaning the default microphone is sometimes set to a device on the other side of the room. I'd rather lock it to the mic on my desk that's always good for this sort of thing.

**Comment by Melvin-Abraham** [comment] 2021-02-12 05:16
@JakeCover This is a duplicate of #22. The feature has been added but not released yet. It will be released soon...

**Comment by Melvin-Abraham** [comment] 2021-02-12 05:16
_Closing as resolved._

**Closed by Melvin-Abraham** 2021-02-12 05:16 UTC
Labels: duplicate
