### ISSUE TITLE
Error: Getting metadata from plugin failed with error: invalid_grant

### ISSUE THREAD

**Issue by davidroth-br** [Melvin-Abraham/Google-Assistant-Unofficial-Desktop-Client#154] opened 2021-02-19 14:48 UTC
Started getting this error after some driver updates:

C:\Users\David\AppData\Local\Programs\Google Assistant\resources\app.asar\node_modules\grpc\src\common.js:62 Auth error:Error: invalid_grant
log @ C:\Users\David\AppData\Local\Programs\Google Assistant\resources\app.asar\node_modules\grpc\src\common.js:62
main.js:492 Error: 14 UNAVAILABLE: Getting metadata from plugin failed with error: invalid_grant
    at Object.exports.createStatusError (C:\Users\David\AppData\Local\Programs\Google Assistant\resources\app.asar\node_modules\grpc\src\common.js:91)
    at ClientDuplexStream._emitStatusIfDone (C:\Users\David\AppData\Local\Programs\Google Assistant\resources\app.asar\node_modules\grpc\src\client.js:233)
    at ClientDuplexStream._receiveStatus (C:\Users\David\AppData\Local\Programs\Google Assistant\resources\app.asar\node_modules\grpc\src\client.js:211)
    at Object.onReceiveStatus (C:\Users\David\AppData\Local\Programs\Google Assistant\resources\app.asar\node_modules\grpc\src\client_interceptors.js:1311)
    at InterceptingListener._callNext (C:\Users\David\AppData\Local\Programs\Google Assistant\resources\app.asar\node_modules\grpc\src\client_interceptors.js:568)
    at InterceptingListener.onReceiveStatus (C:\Users\David\AppData\Local\Programs\Google Assistant\resources\app.asar\node_modules\grpc\src\client_interceptors.js:618)
    at C:\Users\David\AppData\Local\Programs\Google Assistant\resources\app.asar\node_modules\grpc\src\client_interceptors.js:1127

The updated drivers:

- Sonix - Camera - 10.13.19041.13
- Lenovo - System - 2.0.369.1
- Intel Corporation - SoftwareComponent - 2.11.100.3
- Intel Corporation - System - 2.10.100.2
- Synaptics - Mouse - 19.5.19.75
- Synaptics Incorporated - Biometric - 6.0.49.1105

There was also a Windows defender definition update:
Version: 1.331.1372.0
Engine Version: 1.1.17800.5
Platform Version: 4.18.2101.9
Released: 2/19/2021 12:51:21 PM

**Comment by Melvin-Abraham** [comment] 2021-02-19 15:26
@davidroth-br Duplicate of #58.

> You can fix this by deleting the tokens file that was fetched by the application (as per the "Saved Tokens Path") and relaunch the assistant. You will again be presented with "Get Token!" screen. Authenticate your Gmail account again and let it fetch the tokens. This should possibly fix the issue...

**Ref:** https://github.com/Melvin-Abraham/Google-Assistant-Unofficial-Desktop-Client/issues/58#issuecomment-753742483

**Closed by Melvin-Abraham** 2021-02-19 15:26 UTC
Labels: duplicate

**Comment by davidroth-br** [comment] 2021-02-19 15:54
Access Forbidden
Project ugassistant-ba1a5 is shut down and scheduled to be deleted. A project owner can cancel the shutdown on the projects list page.

Got this when trying to "Configure Consent Screen"

**Comment by davidroth-br** [comment] 2021-02-19 15:56
![Screenshot (1)](https://user-images.githubusercontent.com/61717416/108528131-13a7d780-72a1-11eb-843c-1cb3e663e991.png)

**Comment by davidroth-br** [comment] 2021-02-19 15:56
![Screenshot (2)](https://user-images.githubusercontent.com/61717416/108528206-29b59800-72a1-11eb-82f4-4da114e9183e.png)
