### ISSUE TITLE
Mic auto adjusting

### ISSUE THREAD

**Issue by BakaDolev** [Melvin-Abraham/Google-Assistant-Unofficial-Desktop-Client#203] opened 2021-03-02 13:09 UTC
-->

**Describe the bug**
When the Google Assistant app is open it automatically adjust the volume of my microphone 

**To Reproduce**
1. Open The app
2. Mic auto adjusting volume
3. Close app
4. Problem fixed

**Comment by c-l-2oo8** [comment] 2021-03-02 13:48
I guess, you solved it. Anyway, I don't have a mic auto adjust in my settings

**Comment by Melvin-Abraham** [comment] 2021-03-07 07:55
@BakaDolev This issue might be specifically related to your system as the application does not adjust this setting.

**Comment by Melvin-Abraham** [comment] 2021-04-14 17:29
Closing this issue as it does not seem to be caused by the application.

**Closed by Melvin-Abraham** 2021-04-14 17:29 UTC
Labels: 🐛 bug
