### ISSUE TITLE
personal results don't come

### ISSUE THREAD

**Issue by ardubluesky** [Melvin-Abraham/Google-Assistant-Unofficial-Desktop-Client#341] opened 2021-04-25 14:26 UTC
**Describe the bug**
when i ask my linux google assistant to check personal results, it restricts access and asks for permission. when i allow personal results on phone, the assistant app on the phone crashes and when it comes back, it doesn't register my unofficial google assistant on the laptop

**To Reproduce**
1. Go to unofficial linux assistant and ask "check my calendar"
2. assistant asks permission for personal results on phone
3. go to phone
4. click allow
5. google crashes

**Expected behavior**
I expect to give details about my calendar when i ask it

**Screenshots**
![image](https://user-images.githubusercontent.com/64678781/115997111-81ed7b00-a5ff-11eb-9495-af4dc7cf58af.png)

**Desktop (please complete the following information):**
 - POP!_os 20.10
 - 20.10

**Additional context**
this is unofficial linux from snap store and allow personal results for google home mini works from app

**Comment by Melvin-Abraham** [comment] 2021-04-25 15:14
Duplicate of #175

**Comment by Melvin-Abraham** [comment] 2021-04-25 15:15
_Closing as duplicate_

**Closed by Melvin-Abraham** 2021-04-25 15:15 UTC
Labels: duplicate, 🐛 bug
