### ISSUE TITLE
Google Assistant for Windows

### ISSUE THREAD

**Issue by Gremio0087** [Melvin-Abraham/Google-Assistant-Unofficial-Desktop-Client#121] opened 2021-02-13 17:17 UTC
When I instruct Google Assistant for Windows to open a specific webpage or navigate a web page browser to, say for example, Facebook - Google Assistant responds indicating that she is executing the command, but then does not and nothing happens and Google Assistant does not assist me with such basic requests such as navigating to Facebook's webpage on demand.

**Comment by Melvin-Abraham** [comment] 2021-02-17 07:38
@Gremio0087 This is a duplicate of #41.

**Closed** 2021-02-17 07:39 UTC
Labels: duplicate
