### ISSUE TITLE
great idea however asking google to search for anything renders a blank page

### ISSUE THREAD

**Issue by fireheart2008** [Melvin-Abraham/Google-Assistant-Unofficial-Desktop-Client#298] opened 2021-04-14 22:30 UTC
https://i.postimg.cc/6p9wXmjx/screenshot-25.png

**Comment by sumeshir26** [comment] 2021-04-15 15:57
Duplicate of #41

**Comment by Melvin-Abraham** [comment] 2021-04-16 04:17
_Closing as duplicate_

**Closed by Melvin-Abraham** 2021-04-16 04:17 UTC
Labels: duplicate
