### ISSUE TITLE
Unexpected Exception Occured An unexpected error occurred. Error: Tried calling start() before the ready event! 

### ISSUE THREAD

**Issue by AnandM8** [Melvin-Abraham/Google-Assistant-Unofficial-Desktop-Client#81] opened 2021-02-09 05:37 UTC
![google assistant error](https://user-images.githubusercontent.com/78782021/107320684-3418aa80-6ac7-11eb-85d1-ff7ddc78d296.PNG)
 when i open GOOGLE ASSISTANT CLIENT then an error occur as  : ' Unexpected Exception Occured An unexpected error occurred. Error: Tried calling start() before the ready event! '
then it automatically closes itself and open a web page and when i reopen then same error occur and when i press ignore and paste the token code under 
'Get token!
A new browser window is being opened. Login/Select a Google account, accept the permissions and paste the authentication code below.'
then it wont submit when i press submit but once again also it won't submit.
thank you

**Comment by Melvin-Abraham** [comment] 2021-02-09 11:10
@AnandM8 This is a duplicate of issue #39.

This should help:

> Fixed in dd67747. Since, this fix will not be readily available until next release ... you can _temporarily_ disable **Settings** > **Conversation** > **Enable microphone on application startup**

**Ref:** https://github.com/Melvin-Abraham/Google-Assistant-Unofficial-Desktop-Client/issues/39#issuecomment-734111970

**Closed by Melvin-Abraham** 2021-02-09 11:10 UTC
Labels: duplicate
