### ISSUE TITLE
"You are Offline!" Error: Getting metadata from plugin failed with error: invalid_grant - I got this after a few days of using the assistant normally

### ISSUE THREAD

**Issue by DGTBHItzDG** [Melvin-Abraham/Google-Assistant-Unofficial-Desktop-Client#156] opened 2021-02-19 22:08 UTC
**Describe the bug**
Not able to use the program, the program itself seems functional but after a few days of using the Assistant I get an error saying "You are Offline!" and an error "invalid_grant"

**To Reproduce**
1. Install the program
2. Use it normally for a few days
3. Few days later try to use it

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [Windows 10 Build 19042.804]
 - Version [20H2]

**Additional context**

**Comment by kbdharun** [comment] 2021-02-20 01:11
I got the Same Error too A Long time ago, The fix to this is simple just delete the **OAuth 2.0 credentials** and **Key File Path**
And Repeat the Process From Actions Console and Cloud Platform. Then it just works. My best guess is that Google Might be Restricting it by Making the Files to Expire. I think @Melvin-Abraham must look into this issue as the "invalid_grant error" is becoming pretty common.

@DGTBHItzDG I think you get the error in the client like this 

![](https://user-images.githubusercontent.com/26346867/105271118-f659ed80-5bbc-11eb-835e-0c7d2d93e138.png)

**Steps to Reconfigure and get the client back working:**

_Step 1_: Delete the Path Files From your Devices Folder.

_Step 2_: Also Go to the Settings page in client and remove the location of the Key Path file and OAuth 2.0 Credentials

See this image for your Reference 

![Google Assistant Unofficial Client 20-02-2021 06_35_17 AM](https://user-images.githubusercontent.com/26346867/108577197-2e805780-7346-11eb-9d88-0f76635ddb8e.png)

_Step 3_: Now, Restart the Client 

Now the Client must look like this 

![Google Assistant Unofficial Client 20-02-2021 06_35_10 AM](https://user-images.githubusercontent.com/26346867/108577241-5374ca80-7346-11eb-9465-2ca205b3e7ab.png)

_Step 4_: Follow the Steps in Melvin's Guide to Configure the unofficial client for which I had Enclosed the Link Below
 https://github.com/Melvin-Abraham/Google-Assistant-Unofficial-Desktop-Client/wiki/Setup-Authentication-for-Google-Assistant-Unofficial-Desktop-Client
 
 Hope this helps, 
 Regards, Dharun 
 If you have any other methods to fix this issue or any suggestions feel free to comment here.

**Comment by kbdharun** [comment] 2021-02-20 01:15
Duplicate of #58

You can refer to the following comment to fix this issue: https://github.com/Melvin-Abraham/Google-Assistant-Unofficial-Desktop-Client/issues/58#issuecomment-753742483

_Originally posted by @Melvin-Abraham in https://github.com/Melvin-Abraham/Google-Assistant-Unofficial-Desktop-Client/issues/71#issuecomment-765146512_

**Closed** 2021-02-20 05:46 UTC
Labels: duplicate

**Comment by Melvin-Abraham** [comment] 2021-02-21 10:27
> The fix to this is simple just delete the **OAuth 2.0 credentials** and Key File Path and Repeat the Process From Actions Console and Cloud Platform

@kbdharun You do not need to delete the OAuth 2.0 credentials. Just delete the Tokens file (as specified by **Saved Tokens Path**) and in the next launch, you will be presented with "Get Token!" screen. After pasting and submitting the authorization code, you are good to go.

**Comment by kbdharun** [comment] 2021-02-21 13:18
Thanks for the Info , I will edit my original comment with the new change mentioned by you.
