### ISSUE TITLE
Search

### ISSUE THREAD

**Issue by Emilbangmik** [Melvin-Abraham/Google-Assistant-Unofficial-Desktop-Client#201] opened 2021-03-01 13:25 UTC
The assistant is not able to search on google, or doesn't show the results

**Comment by LinqLover** [comment] 2021-03-01 16:56
Duplicate of #41

**Comment by Melvin-Abraham** [comment] 2021-03-07 07:55
_Closing as duplicate_

**Closed by Melvin-Abraham** 2021-03-07 07:55 UTC
Labels: duplicate
