### ISSUE TITLE
Error: Tried calling start() before the ready event!

### ISSUE THREAD

**Issue by psydex** [Melvin-Abraham/Google-Assistant-Unofficial-Desktop-Client#118] opened 2021-02-13 14:34 UTC
So I was following closely the installation guide but it was timing out on last step of the setup (namely when you paste the authentication code and click submit). So I started from scratch and now I'm getting this error right before where I need to paste the authentication code.

![image](https://user-images.githubusercontent.com/5594251/107852407-33f71280-6e19-11eb-9fa7-9752cc04ae05.png)
Relaunching won't help and ignoring the error just render the submit button unusable.
What am I doing wrong?

**Comment by Melvin-Abraham** [comment] 2021-02-13 15:39
@psydex This is a duplicate of issue #39.

This should help:

> Fixed in dd67747. Since, this fix will not be readily available until next release ... you can _temporarily_ disable **Settings** > **Conversation** > **Enable microphone on application startup**

**Ref:** https://github.com/Melvin-Abraham/Google-Assistant-Unofficial-Desktop-Client/issues/39#issuecomment-734111970

PS: If this helps, do close the issue...

**Comment by psydex** [comment] 2021-02-13 16:48
It worked!

**Closed** 2021-02-13 16:48 UTC
