### ISSUE TITLE
[Bug?]Constant use of microphone

### ISSUE THREAD

**Issue by teenspirit7** [Melvin-Abraham/Google-Assistant-Unofficial-Desktop-Client#65] opened 2021-01-11 16:05 UTC
Hi, until there is 'Ok Google' support is there a need for the app to constantly be 'using your microphone' according to windows showing the mic icon in the taskbar?

Windows 10 Latest

Love the app by the way, great job.

Thanks,

![image](https://user-images.githubusercontent.com/1161466/104205831-c5442500-5426-11eb-8d93-5c2d98ee29cb.png)

**Comment by Melvin-Abraham** [comment] 2021-01-11 17:13
Duplicate of #30. This issue has already been reported and has been fixed 😃. For bug details, refer https://github.com/Melvin-Abraham/Google-Assistant-Unofficial-Desktop-Client/issues/30#issuecomment-718846607

The fix will be available in the next release of this app. Till then if you want to test it, you can clone this repo and run it locally (see [How to build?](https://github.com/Melvin-Abraham/Google-Assistant-Unofficial-Desktop-Client#how-to-build)).

_Closing as Duplicate_

**Closed by Melvin-Abraham** 2021-01-11 17:13 UTC
Labels: duplicate
