### ISSUE TITLE
Escape to dismiss

### ISSUE THREAD

**Issue by SjorsMaster** [Melvin-Abraham/Google-Assistant-Unofficial-Desktop-Client#234] opened 2021-03-11 10:04 UTC
Please consider an "esc to dissmiss assistant" feature.

**Comment by esau-morais** [comment] 2021-03-11 10:09
Duplicate of #92

**Comment by esau-morais** [comment] 2021-03-11 10:12
This feature was already implemented on the built version. If you just installed the latest release, it still not available. Why I recommend is to build in your own machine in the meantime.

**Comment by Melvin-Abraham** [comment] 2021-03-14 16:40
@SjorsMaster This feature has already been implemented in ede676c2

**Comment by Melvin-Abraham** [comment] 2021-03-14 16:40
_Closing as resolved_

**Closed by Melvin-Abraham** 2021-03-14 16:40 UTC
