### ISSUE TITLE
Could not connect to internet!  Error: invalid_grant

### ISSUE THREAD

**Issue by psydex** [Melvin-Abraham/Google-Assistant-Unofficial-Desktop-Client#160] opened 2021-02-20 21:02 UTC
**Describe the bug**
Assistant could not connect to the internet

**To Reproduce**
1. launch client
2. press on the mic icon
3. Error: Getting metadata from plugin failed with error: invalid_grant

**Screenshots**
![image](https://user-images.githubusercontent.com/5594251/108608445-9929a580-73cf-11eb-8556-4bbd1efdbb24.png)

**Desktop (please complete the following information):**
 - Windows 10 Pro
 - Assistant: Latest (rc2)

**Comment by anuragdandge** [comment] 2021-02-21 08:41
I'm also getting this same error

**Comment by Melvin-Abraham** [comment] 2021-02-21 10:20
Duplicate of #58. You can refer to the following comment to fix this issue: https://github.com/Melvin-Abraham/Google-Assistant-Unofficial-Desktop-Client/issues/58#issuecomment-753742483

**PS:** This issue has already been addressed within the source as per ebc91ef just not released yet.

**Comment by Melvin-Abraham** [comment] 2021-02-21 10:20
_Closing as duplicate_

**Closed by Melvin-Abraham** 2021-02-21 10:20 UTC
Labels: duplicate
