### ISSUE TITLE
[🤔Request feature] : Make google assistant routines (easy dialogs program create)

### ISSUE THREAD

**Issue by minecraftpvpmax** [Melvin-Abraham/Google-Assistant-Unofficial-Desktop-Client#225] opened 2021-03-07 12:36 UTC
Hey ! I want to do a suggestion ! when you say to google assistant -"Routines settings" or in French -"Routines" you can do personalised commands, test yourself.
I use this ALL TIME. Please add it. I give screenshots but that more expansive than what i show.
![Screenshot_20210307-132631](https://user-images.githubusercontent.com/75168136/110240009-23cee080-7f4a-11eb-9724-5b9e615fdda4.jpg)
![Screenshot_20210307-132639](https://user-images.githubusercontent.com/75168136/110240010-24677700-7f4a-11eb-9e94-fc87e9e10fb1.jpg)
![Screenshot_20210307-132649](https://user-images.githubusercontent.com/75168136/110240011-25000d80-7f4a-11eb-8e18-6e9ba58db910.jpg)
![Screenshot_20210307-132750](https://user-images.githubusercontent.com/75168136/110240012-2598a400-7f4a-11eb-8707-85296d10b1d1.jpg)
![Screenshot_20210307-132812](https://user-images.githubusercontent.com/75168136/110240013-26313a80-7f4a-11eb-8ca6-577f61ac4d0b.jpg)
![Screenshot_20210307-132820](https://user-images.githubusercontent.com/75168136/110240015-27626780-7f4a-11eb-8349-7f4eb21295d4.jpg)
![Screenshot_20210307-132854](https://user-images.githubusercontent.com/75168136/110240018-28939480-7f4a-11eb-87ab-380aa4589d7c.jpg)

**Comment by Melvin-Abraham** [comment] 2021-03-14 17:56
Duplicate of #83
This will be worked upon once all the necessary bug fixes and enhancements are addressed :)

**Comment by minecraftpvpmax** [comment] 2021-03-20 16:57
Thx !

**Closed** 2021-03-20 16:57 UTC
Labels: duplicate, ✨ enhancement
