### ISSUE TITLE
Failed to get Tokens

### ISSUE THREAD

**Issue by csansoon** [Melvin-Abraham/Google-Assistant-Unofficial-Desktop-Client#112] opened 2021-02-13 10:53 UTC
I followed all the steps to authenticate with my account. Then at the final step, when I paste the token Google gives me to the app, it just waits 10 seconds and shows an error Message:

> **Failed to get Tokens**
> Assistant failed to fetch the tokens from server. Either the auth code is invalid or the rate limit might have exceeded. Try selecting a different Google Account.
> _Error: Error getting tokens_

I tried multiple times and checked if I did all the steps right and I can't find a solution.

![image](https://user-images.githubusercontent.com/57395395/107848143-7278d700-6df1-11eb-932e-d7eeaf0fb9ac.png)

**Comment by GlenIssac** [comment] 2021-02-13 11:08
Dude how do you even open the "app"

**Comment by sirloinofbeef** [comment] 2021-02-13 11:20
What OS are you using?
What is your saved tokens path? The program will read / write access to the path.

**Comment by Melvin-Abraham** [comment] 2021-02-13 11:40
@csansoon That is actually related to Google Cloud's daily rate limiting. You can retry this the next day and it should work...

**Comment by csansoon** [comment] 2021-02-13 11:42
> Dude how do you even open the "app"

Win+Shift+A in Windows

**Comment by csansoon** [comment] 2021-02-13 13:33
Okay I solved it for me!
I think my problem was with administrative access. I changed the location of the **Key File Path** as well as the **Saved Tokens Path** to my Documents folder, so the app now has access to it! Now it's all working fine.

![image](https://user-images.githubusercontent.com/57395395/107848388-65f57e00-6df3-11eb-80c8-5cc2dcd3153c.png)

**Comment by Melvin-Abraham** [comment] 2021-02-13 15:42
@csansoon I assume the issue is resolved, so I'll close this...

**Closed by Melvin-Abraham** 2021-02-13 15:42 UTC
