### ISSUE TITLE
Error: Getting metadata from plugin failed with error: invalid_grant

### ISSUE THREAD

**Issue by NITHINLYCANZ** [Melvin-Abraham/Google-Assistant-Unofficial-Desktop-Client#305] opened 2021-04-15 16:01 UTC
![Google Assistant Unofficial Client 15-04-2021 09_28_19 PM](https://user-images.githubusercontent.com/81744339/114900858-e22b3280-9e31-11eb-8e37-c0bf3a75acba.png)

**Comment by sumeshir26** [comment] 2021-04-15 16:16
Duplicate of #295

Try redoing the Configuration Process.

**Comment by Melvin-Abraham** [comment] 2021-04-16 04:13
@NITHINLYCANZ Refer [this section](https://github.com/Melvin-Abraham/Google-Assistant-Unofficial-Desktop-Client/wiki/Frequently-Asked-Questions-(FAQ)#how-do-i-fix-invalid_grant-error) of the FAQ to address this issue for now.

**Comment by Melvin-Abraham** [comment] 2021-04-16 04:13
_Closing as duplicate_

**Closed by Melvin-Abraham** 2021-04-16 04:13 UTC
Labels: duplicate, 🐛 bug

**Comment by webjoaoneto** [comment] 2021-09-14 14:04
Will this problem happen forever?

**Comment by im-coder-lg** [comment] 2021-09-14 15:39
Nah, it's fixed.

**Comment by Melvin-Abraham** [comment] 2021-09-15 06:34
> Will this problem happen forever?

@webjoaoneto Yes. This is actually due to the usage of the token past its expiry. Keeping this in mind, in the next version, you will be able to reset the tokens right from the assistant itself without navigating away and figuring out where the access token is located.
