### ISSUE TITLE
reminder notifications on desktop

### ISSUE THREAD

**Issue by Netherquark** [Melvin-Abraham/Google-Assistant-Unofficial-Desktop-Client#224] opened 2021-03-07 06:18 UTC
**Is your feature request related to a problem? Please describe.**
I can set reminders from the desktop assistant, but I only get the notifications on my phone.

**Describe the solution you'd like**
If there is somehow, a way, to capture assistant notifications, like tell me a fact, reminder notifs, weather notifs etc then I would love it if they were displayed on the desktop, similar to how discord or chrome notifs show up on windows, in the notification pane

**Comment by Melvin-Abraham** [comment] 2021-03-07 07:37
Duplicate of #30

This issue has already been reported and has been fixed. For bug details, refer https://github.com/Melvin-Abraham/Google-Assistant-Unofficial-Desktop-Client/issues/30#issuecomment-718846607

The fix will be available in the next release of this app. Till then if you want to test it, you can clone this repo and run it locally (see [How to build?](https://github.com/Melvin-Abraham/Google-Assistant-Unofficial-Desktop-Client#how-to-build)).

**Comment by Melvin-Abraham** [comment] 2021-03-07 07:38
_Closing as duplicate_

**Closed by Melvin-Abraham** 2021-03-07 07:38 UTC
Labels: ✨ enhancement, 🐛 bug
