### ISSUE TITLE
The Desktop Client Shows, Error: Getting metadata from plugin failed with error: invalid_grant

### ISSUE THREAD

**Issue by kbdharun** [Melvin-Abraham/Google-Assistant-Unofficial-Desktop-Client#71] opened 2021-01-21 02:20 UTC
**Describe the bug**
My Computer has Internet and It works properly but the Client Shows this message
You are Offline!
Please check your Internet Connection...
Error: Getting metadata from plugin failed with error: invalid_grant

**Expected behavior**
To Work Properly without any hiccups. 

**Screenshots**

![Google Assistant Unofficial Client 21-01-2021 07_47_38 AM](https://user-images.githubusercontent.com/26346867/105271118-f659ed80-5bbc-11eb-835e-0c7d2d93e138.png)

**Desktop :**
 - OS: Windows 10 Home  Build 19042
 - Version : 10.0.19042
 
**Additional context**
The Client Worked Perfectly till last week. Since then I am getting this error message

**Comment by Melvin-Abraham** [comment] 2021-01-22 05:53
Duplicate of #58

You can refer to the following comment to fix this issue: https://github.com/Melvin-Abraham/Google-Assistant-Unofficial-Desktop-Client/issues/58#issuecomment-753742483

**Comment by Melvin-Abraham** [comment] 2021-01-22 05:53
_Closing as Duplicate_

**Closed by Melvin-Abraham** 2021-01-22 05:53 UTC
Labels: duplicate

**Comment by kbdharun** [comment] 2021-01-22 07:53
Thanks, Sorry I didn't know this issue has already been addressed
