### ISSUE TITLE
"You are offline!" error

### ISSUE THREAD

**Issue by Geryno** [Melvin-Abraham/Google-Assistant-Unofficial-Desktop-Client#251] opened 2021-03-19 22:10 UTC
Hi. It was working for me, until someday it just wasn't. Now I get this error message at startup:
![image](https://user-images.githubusercontent.com/47223962/111847006-a7a4a780-8910-11eb-933d-f4102f2520a2.png)

**Desktop** 
- OS: Windows 10 Home 64 bit 0.0.18363, build 18363
- v1.0.0-rc.2

**Comment by esau-morais** [comment] 2021-03-19 23:06
Duplicate of several issues.

**Comment by esau-morais** [comment] 2021-03-19 23:08
Please, refer to [this section](https://github.com/Melvin-Abraham/Google-Assistant-Unofficial-Desktop-Client/wiki/Frequently-Asked-Questions-(FAQ)#how-do-i-fix-invalid_grant-error) at the FAQ.

**Comment by Melvin-Abraham** [comment] 2021-03-20 03:04
_Closing as duplicate_

**Closed** 2021-03-20 03:04 UTC
Labels: duplicate, 🐛 bug
