### ISSUE TITLE
Setting Cog Wheel Does Nothing

### ISSUE THREAD

**Issue by willgk** [Melvin-Abraham/Google-Assistant-Unofficial-Desktop-Client#125] opened 2021-02-14 01:29 UTC
Using latest release, was going through the wiki to get it set up. I installed it to the default location (all users) and when I open the app, it comes up just fine, win+shift+a brings it up as well, however the Cog Wheel (upper left) does nothing at all. I am unable to configure the token for authentication. I couldn't find a log anywhere that had data to show what may be happening.

**Comment by Sujith0Nair** [comment] 2021-02-14 06:59
Same +1

**Comment by Sujith0Nair** [comment] 2021-02-14 07:27
I'm not sure of why the settings option is in the disable class though. But I overwrote the code in main.js file as provided in the image and everything seems to be working fine now.
![image](https://user-images.githubusercontent.com/39736056/107871042-1d59c580-6ec4-11eb-9714-7b951a9ac1e2.png)

**Comment by Melvin-Abraham** [comment] 2021-02-14 08:24
@willgk @Sujith0Nair Duplicate of #45 and #85.

> Seems like you are in the welcome screen. If you are, you will have to click through the **"Get Started"** and **"Proceed"** buttons before you can access settings.
>
> ![Welcome Screen](https://user-images.githubusercontent.com/26056183/107728586-7e429b80-6d14-11eb-98d5-f0ff63891702.png)

**Ref:** https://github.com/Melvin-Abraham/Google-Assistant-Unofficial-Desktop-Client/issues/85#issuecomment-777952555

**Comment by Melvin-Abraham** [comment] 2021-02-14 08:24
_Closing as Duplicate_

**Closed by Melvin-Abraham** 2021-02-14 08:24 UTC
