### ISSUE TITLE
Mic always on

### ISSUE THREAD

**Issue by DarkFlame57** [Melvin-Abraham/Google-Assistant-Unofficial-Desktop-Client#72] opened 2021-01-24 15:41 UTC
Hello, in pavucontrol it looks like the mic is always on, please make it possible to disable this behavior. 
![123](https://user-images.githubusercontent.com/49563183/105635425-a1d39e00-5e5a-11eb-8542-24befac69238.png)

**Comment by Melvin-Abraham** [comment] 2021-01-25 10:11
Duplicate of #30 and #65

This issue has already been reported and has been fixed. For bug details, refer https://github.com/Melvin-Abraham/Google-Assistant-Unofficial-Desktop-Client/issues/30#issuecomment-718846607

The fix will be available in the next release of this app. Till then if you want to test it, you can clone this repo and run it locally (see [How to build?](https://github.com/Melvin-Abraham/Google-Assistant-Unofficial-Desktop-Client#how-to-build)).

**Comment by Melvin-Abraham** [comment] 2021-01-25 10:11
_Closing as Duplicate_

**Closed by Melvin-Abraham** 2021-01-25 10:11 UTC
Labels: duplicate
