### ISSUE TITLE
[🐛 Bug]: Authorization Error

### ISSUE THREAD

**Issue by pastinepolenta** [Melvin-Abraham/Google-Assistant-Unofficial-Desktop-Client#669] opened 2022-03-09 12:31 UTC
### What went wrong?

Error 400: invalid_request

You can't sign in to this app because it doesn't comply with Google's OAuth 2.0 policy for keeping apps secure.

You can let the app developer know that this app doesn't comply with one or more Google validation rules.
Request Details
The content in this section has been provided by the app developer. This content has not been reviewed or verified by Google.
If you’re the app developer, make sure that these request details comply with Google policies.
redirect_uri: urn:ietf:wg:oauth:2.0:oob

### What did you expect to happen?

I can authorize the app to get the token

### Steps to reproduce the bug

1. follow the registration process
2. at the "get the token" step the browser opens
3. Google auth page throws that error

### App Version

v1.0.0

### OS Version

Ubuntu 21.10

### Pre-submission Checklist

- [X] I have checked [the issue tracker](https://github.com/Melvin-Abraham/Google-Assistant-Unofficial-Desktop-Client/issues?q=is%3Aissue+label%3A%22%F0%9F%90%9B+bug%22) and didn't find any duplicate issue
- [X] I have checked the [Frequently Asked Questions (FAQs)](https://github.com/Melvin-Abraham/Google-Assistant-Unofficial-Desktop-Client/wiki/Frequently-Asked-Questions-(FAQ)) and can confirm that there's no fixes or workarounds for this issue
- [X] This issue only covers one particular bug or issue

**Comment by sumeshir26** [comment] 2022-03-09 14:25
Thsi is a duplicate issue, plase dont check the I have loked at the duplicate isues checkboz without actuallay loking

**Comment by pastinepolenta** [comment] 2022-03-09 14:35
I did search, none of the issues mention a 400 invalid request with that message. They mention different cases. If you have found a duplicate please link it and close this one.

**Comment by sumeshir26** [comment] 2022-03-10 04:18
Duplicate of #668

**Comment by Melvin-Abraham** [comment] 2022-03-13 12:56
Thank you for reporting this issue. Since, it's already a duplicate of the above mentioned issue, this issue will be closed and any further updates regarding this could be tracked there.

**Comment by Melvin-Abraham** [comment] 2022-03-13 12:56
Closing as duplicate

**Closed by Melvin-Abraham** 2022-03-13 12:56 UTC
Labels: 🐛 bug, duplicate
