### ISSUE TITLE
[🐛 Bug]: Web search

### ISSUE THREAD

**Issue by creeperlulu** [Melvin-Abraham/Google-Assistant-Unofficial-Desktop-Client#596] opened 2021-12-05 20:23 UTC
### What went wrong?

I tried to say Play some music and it respond with no results

### What did you expect to happen?

I wanted it to open Spotify or Youtube

### Steps to reproduce the bug

1.Say Play some music
2.You should see "Results from Youtube or something like this"
3.No results appearing

### App Version

v1.0.0

### OS Version

Windows 10 21H1 Build 19043.1387

### :information_source: Platform Info
Running on **Windows_NT x64 10.0.19043**
![image](https://user-images.githubusercontent.com/74853862/144762563-6fee2e98-46fe-4466-9caf-e16877f708a6.png)
![image](https://user-images.githubusercontent.com/74853862/144762564-520c5a68-45a4-4e40-ae49-0a7e53bd03b6.png)

### Pre-submission Checklist

- [X] I have checked [the issue tracker](https://github.com/Melvin-Abraham/Google-Assistant-Unofficial-Desktop-Client/issues?q=is%3Aissue+label%3A%22%F0%9F%90%9B+bug%22) and didn't find any duplicate issue
- [X] I have checked the [Frequently Asked Questions (FAQs)](https://github.com/Melvin-Abraham/Google-Assistant-Unofficial-Desktop-Client/wiki/Frequently-Asked-Questions-(FAQ)) and can confirm that there's no fixes or workarounds for this issue
- [X] This issue only covers one particular bug or issue

**Comment by im-coder-lg** [comment] 2021-12-06 02:10
Hmm... These aren't fully integrated, kind of. Can you try enabling Personal Results? I will post the link shortly.

**Comment by im-coder-lg** [comment] 2021-12-06 03:57
[This one.](https://gist.github.com/im-coder-lg/23fc93cbf983b36b21641563ed4f3d4e)

**Comment by creeperlulu** [comment] 2021-12-06 06:56
Hello,

I already tried this. Everytime I do this, I click on the notification on
my phone and nothing happens... Is this because I'm in France ?

Thank you

**Comment by im-coder-lg** [comment] 2021-12-06 07:28
Is it Android or iOS?

**Comment by creeperlulu** [comment] 2021-12-06 16:36
I'm running on Android 12 on a Google Pixel 4a.
Do you want my version of Google assistant (Android)?

**Comment by im-coder-lg** [comment] 2021-12-06 17:23
Can you show some recordings please? One from your PC and another one from the Pixel? Make sure to hide personal info if you wish.

**Comment by Melvin-Abraham** [comment] 2021-12-06 17:48
Duplicate of #41

**Comment by Melvin-Abraham** [comment] 2021-12-06 17:49
> Can you try enabling Personal Results

@im-coder-lg It doesn't seem to be related to personal results

**Comment by Melvin-Abraham** [comment] 2021-12-06 17:50
_Closing as duplicate_

You may track any progress regarding this issue in the above mentioned issue.

**Closed by Melvin-Abraham** 2021-12-06 17:50 UTC
Labels: 🐛 bug
