### ISSUE TITLE
macOS 11.3 Beta Uncaught Exception on launch

### ISSUE THREAD

**Issue by GeorgePr** [Melvin-Abraham/Google-Assistant-Unofficial-Desktop-Client#99] opened 2021-02-12 16:06 UTC
I installed the app on macOS Big Sur 11.3 Beta 1 (20E5172i) and I am stuck in this window. I haven't been able to view the main screen of the app. I am using the latest version (1.0.0-rc2). Thank you.

![Screen Shot 2021-02-12 at 18 02 24](https://user-images.githubusercontent.com/6285836/107791652-de5d3000-6d5c-11eb-80a8-bc6f8661d479.png)

**Comment by Melvin-Abraham** [comment] 2021-02-13 05:29
@GeorgePr Duplicate of #35.

This is a bug which occurs due to passing a floating-point number to the `setPosition()` function, which is calculated based on your screen size. Thus, the only way to get around it for the time-being is to clone this repo (via `git clone`) and build it yourself (see [How to build](https://github.com/Melvin-Abraham/Google-Assistant-Unofficial-Desktop-Client#how-to-build)) since _**it has been fixed within the source but not released yet.**_

You can learn more about this bug [here](https://github.com/Melvin-Abraham/Google-Assistant-Unofficial-Desktop-Client/issues/35#issuecomment-726725640).

**Comment by Melvin-Abraham** [comment] 2021-02-13 05:30
_Closing as duplicate_

**Closed by Melvin-Abraham** 2021-02-13 05:30 UTC
Labels: duplicate
