### ISSUE TITLE
More integration with windows 10?

### ISSUE THREAD

**Issue by Oi-Baba** [Melvin-Abraham/Google-Assistant-Unofficial-Desktop-Client#277] opened 2021-04-07 16:50 UTC
Is it possible to integrate this more with windows like setting alarms and timers for example?

**Comment by Melvin-Abraham** [comment] 2021-04-14 17:16
Duplicate of #33.

**Comment by Melvin-Abraham** [comment] 2021-04-14 17:16
_Closing as duplicate_

**Closed by Melvin-Abraham** 2021-04-14 17:16 UTC
Labels: duplicate
