### ISSUE TITLE
javascript error on launch

### ISSUE THREAD

**Issue by yossijo** [Melvin-Abraham/Google-Assistant-Unofficial-Desktop-Client#150] opened 2021-02-18 19:56 UTC
**Describe the bug**
when launching app a javascript error pops up & the app freezes
possibly related to windows insider version

**To Reproduce**
1. install latest windows insider preview (maybe)
2. launch unofficial assistant app 
3. See error

**Expected behavior**
should work 

**Screenshots**
![Screenshot 2021-02-18 145435](https://user-images.githubusercontent.com/79281752/108413670-49918100-71f9-11eb-8e12-6fd51bceec9a.png)

**Desktop (please complete the following information):**
 - OS: [e.g. Windows 10 insider preview  21313]
 - Version [ 1.0.0-rc.2]

**Additional context**
didnt happen on other computer on windows insider

**Comment by esau-morais** [comment] 2021-02-18 20:02
Duplicate of #80

**Comment by yossijo** [comment] 2021-02-18 20:11
resolved when changing my text size to 100    was on 125

**Comment by yossijo** [comment] 2021-02-18 20:18
happens when the Make Text Bigger is at 157 + approx

**Comment by Melvin-Abraham** [comment] 2021-02-19 05:41
@yossijo Unfortunately it depends on the screen resolution. It calculates half of the resolution (+ or - some offset) and if the calculated value is a decimal, that causes an error. This has been fixed in the source but just not released yet. To test if the issue is fixed, you can clone the repo and build it yourself (check the readme for commands to run/build).

**Comment by Melvin-Abraham** [comment] 2021-02-19 05:42
_Closing as duplicate_

**Closed by Melvin-Abraham** 2021-02-19 05:42 UTC
Labels: duplicate
