### ISSUE TITLE
[🐛 Bug]: 

### ISSUE THREAD

**Issue by DikshitRJ** [Melvin-Abraham/Google-Assistant-Unofficial-Desktop-Client#587] opened 2021-11-24 12:11 UTC
### What went wrong?

The assistant says "This came back from a search" even though there is no search result for it
![image](https://user-images.githubusercontent.com/84832364/143235744-b3f8fc22-7378-47cd-b29f-b3a43e40fbb0.png)

### What did you expect to happen?

I expected to see a proper search result, because the question i asked was a proper question. If there was no search result for it, the assistant could have simply said "I dont Know".

### Steps to reproduce the bug

1. Search for something random

### App Version

v1.0.0

### OS Version

windows 11

### Relevant Assets

![image](https://user-images.githubusercontent.com/84832364/143236070-1ffa7bea-78d4-4e9c-a9c5-8cd2970199db.png)

### Pre-submission Checklist

- [X] I have checked [the issue tracker](https://github.com/Melvin-Abraham/Google-Assistant-Unofficial-Desktop-Client/issues?q=is%3Aissue+label%3A%22%F0%9F%90%9B+bug%22) and didn't find any duplicate issue
- [X] I have checked the [Frequently Asked Questions (FAQs)](https://github.com/Melvin-Abraham/Google-Assistant-Unofficial-Desktop-Client/wiki/Frequently-Asked-Questions-(FAQ)) and can confirm that there's no fixes or workarounds for this issue
- [X] This issue only covers one particular bug or issue

**Comment by im-coder-lg** [comment] 2021-11-24 15:07
I think it's personal results, seen a LOT of this, try this link, it's a comment by me on another issue 27 days ago as of typing this.
https://github.com/Melvin-Abraham/Google-Assistant-Unofficial-Desktop-Client/issues/573#issuecomment-953993432

**Comment by Melvin-Abraham** [comment] 2021-11-25 03:15
> I think it's personal results

@im-coder-lg Unfortunately, this cannot be fixed by enabling personal results. If it were caused by this, the user would have been prompted to enable personal results. This feature used to work initially but has been changed later on by Google thus the issue.

> seen a LOT of this

This issue is a duplicate of #41 and many others

**Comment by Melvin-Abraham** [comment] 2021-11-25 03:16
_Closing as duplicate_

**Closed by Melvin-Abraham** 2021-11-25 03:16 UTC
Labels: 🐛 bug, duplicate

**Comment by im-coder-lg** [comment] 2021-11-25 03:19
Oh, okay. Looks like I need to see the issues properly.
