### ISSUE TITLE
App is using mic all the time when open

### ISSUE THREAD

**Issue by kneelesh48** [Melvin-Abraham/Google-Assistant-Unofficial-Desktop-Client#229] opened 2021-03-09 16:09 UTC
**Describe the bug**
App is using mic all the time when open

**To Reproduce**
1. Open the app on Windows

**Expected behavior**
App should only use mic when it is activated with Win+Shift+A or when it is open in Task Bar.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 10 Build 2004

**Additional context**

**Comment by NeckBeardPrince** [comment] 2021-03-09 16:57
This is also happening on macOS.

**Comment by JosephM101** [comment] 2021-03-09 18:02
Yeah, I noticed that too. If it's going to do that, they might as well add the "Okay/Hey, Google" voice triggers.

**Comment by Melvin-Abraham** [comment] 2021-03-10 07:50
Duplicate of #30

This issue has already been reported and has been fixed. For bug details, refer https://github.com/Melvin-Abraham/Google-Assistant-Unofficial-Desktop-Client/issues/30#issuecomment-718846607

The fix will be available in the next release of this app. Till then if you want to test it, you can clone this repo and run it locally (see [How to build?](https://github.com/Melvin-Abraham/Google-Assistant-Unofficial-Desktop-Client#how-to-build)).

**Comment by Melvin-Abraham** [comment] 2021-03-10 07:50
_Closing as duplicate_

**Closed by Melvin-Abraham** 2021-03-10 07:50 UTC
Labels: 🐛 bug

**Comment by esau-morais** [comment] 2021-03-10 14:59
@kneelesh48, I agree with you, but we have to be patient in the meantime because there are a lot of surprises coming soon ;)
