### ISSUE TITLE
You are offline - invalid_grant

### ISSUE THREAD

**Issue by dan0O0** [Melvin-Abraham/Google-Assistant-Unofficial-Desktop-Client#162] opened 2021-02-21 14:57 UTC
![2021-02-21 15_54_36-Google Assistant Unofficial Client](https://user-images.githubusercontent.com/43136638/108628853-4b5b7e80-745d-11eb-87ac-849fd3df45ab.png)

this is the issue i get. I have not changed anything. the assistant was working 2 days before but now it does not think im online.
how can i fix this?

**Comment by Melvin-Abraham** [comment] 2021-02-21 15:14
@dan0O0 Duplicate of #58. You can refer to the following comment to fix this issue: https://github.com/Melvin-Abraham/Google-Assistant-Unofficial-Desktop-Client/issues/58#issuecomment-753742483

**PS:** This issue has already been addressed within the source as per ebc91ef just not released yet.

**Closed** 2021-02-21 15:14 UTC
Labels: duplicate
