### ISSUE TITLE
[🐛 Bug]: 

### ISSUE THREAD

**Issue by FelipeDDMM** [Melvin-Abraham/Google-Assistant-Unofficial-Desktop-Client#783] opened 2022-10-09 04:11 UTC
### What went wrong?

o app esta com erro de tocken 

### What did you expect to happen?

eu espera usar o google assistente 

### Steps to reproduce the bug

quando voce faz as etapas instruidas na pagina do autor e baixa a key ela nao é aceita

### App Version

v1.0.0-rc.2

### OS Version

windows 10 21h2

### Pre-submission Checklist

- [X] I have checked [the issue tracker](https://github.com/Melvin-Abraham/Google-Assistant-Unofficial-Desktop-Client/issues?q=is%3Aissue+label%3A%22%F0%9F%90%9B+bug%22) and didn't find any duplicate issue
- [X] I have checked the [Frequently Asked Questions (FAQs)](https://github.com/Melvin-Abraham/Google-Assistant-Unofficial-Desktop-Client/wiki/Frequently-Asked-Questions-(FAQ)) and can confirm that there's no fixes or workarounds for this issue
- [X] This issue only covers one particular bug or issue

**Comment by im-coder-lg** [comment] 2022-10-09 15:30
Translation if needed(Portuguese)

<details>
<summary>Translation</summary>

What went wrong?
the app has a tocken error

What did you expect to happen?
i hope to use google assistant

Steps to reproduce the bug
when you do the steps instructed on the author's page and download the key it is not accepted

</details>

> Did you follow the steps properly?
English

> Você seguiu os passos corretamente?
Portuguese

**Comment by Melvin-Abraham** [comment] 2022-10-15 11:22
This seems to be a duplicate issue. Please refer to [Unable to process request due to missing initial state or localhost refused to connect (FAQ)](https://github.com/Melvin-Abraham/Google-Assistant-Unofficial-Desktop-Client/wiki/Frequently-Asked-Questions-(FAQ)#fix-unable-to-process-request-due-to-missing-initial-state-or-localhost-refused-to-connect)

**Comment by Melvin-Abraham** [comment] 2022-10-30 08:33
This issue has been fixed in [`v1.1.0`](https://github.com/Melvin-Abraham/Google-Assistant-Unofficial-Desktop-Client/releases/tag/v1.1.0)

**Comment by Melvin-Abraham** [comment] 2022-10-30 08:33
_Closing as resolved_

**Closed by Melvin-Abraham** 2022-10-30 08:33 UTC
Labels: 🐛 bug
