### ISSUE TITLE
Encountering "offline" error due to invalid_grant

### ISSUE THREAD

**Issue by SpoiledSoul** [Melvin-Abraham/Google-Assistant-Unofficial-Desktop-Client#166] opened 2021-02-21 22:34 UTC
**Describe the bug**
Opening Assistant results in "You Are Offline!" error:
`Error: Getting metadata from plugin failed with error: invalid_grant`

**To Reproduce**
1. Start system
2. Open Assistant with hotkey (Win + Shift + A)

**Expected behavior**
I expected the microphone input (enabled on startup) to allow me to speak to Assistant.

**Screenshots**
![Screenshot 2021-02-21 172536](https://user-images.githubusercontent.com/15527752/108640989-cd9e6f80-746a-11eb-856b-90b2f72fb2cc.png)

**Desktop:**
 - OS: Windows 10 Build 19042
 - Version 1.0.0-rc.2

**Comment by esau-morais** [comment] 2021-02-22 00:16
Duplicate of #58

[See comment](https://github.com/Melvin-Abraham/Google-Assistant-Unofficial-Desktop-Client/issues/58#issuecomment-753742483)

**Comment by kbdharun** [comment] 2021-02-22 02:34
Duplicate of #58

You can refer to the following comment to fix this issue: #58 (comment)

**Closed** 2021-02-22 17:20 UTC
Labels: duplicate
