### ISSUE TITLE
Electron: Loading non-context-aware native module in renderer

### ISSUE THREAD

**Issue by leabergero** [Melvin-Abraham/Google-Assistant-Unofficial-Desktop-Client#327] opened 2021-04-21 20:22 UTC
**The Bug**
Hi guys.

Today I install g-assist via Snapcraft (SNAP) on Archlinux, when I start g-assist this one show the desktop icon and then close, but the process its still alive, and via linux console i can see its a Electron issue.

**Console Exit**
$ g-assist
WARNING: cgroup v2 is not fully supported yet, proceeding with partial confinement
WARNING: Kernel has no file descriptor comparison support: Operation not permitted
**(node:304416) Electron: Loading non-context-aware native module in renderer: '/run/user/1000/snap.g-assist/.org.chromium.Chromium.VefUW1'. This is deprecated, see https://github.com/electron/electron/issues/18397.**

And I have to kill the process with Ctrl+C

**Desktop info:**
 - OS: Archlinux x86_64 GNU/Linux
 - Version 5.11.15-arch1-2

**Comment by Melvin-Abraham** [comment] 2021-04-24 06:33
This is a duplicate of #247

> This is due to a native module, `grpc`, used by this project and is just a warning which could be ignored for now. However, if there's a way to get it working via `grpc-js` (for both typed and voice queries), please do share it here.

**Ref:** https://github.com/Melvin-Abraham/Google-Assistant-Unofficial-Desktop-Client/issues/247#issuecomment-808757121

**Comment by Melvin-Abraham** [comment] 2021-04-24 06:33
_Closing as duplicate_

**Closed by Melvin-Abraham** 2021-04-24 06:33 UTC
Labels: duplicate, 🐛 bug

**Comment by Melvin-Abraham** [comment] 2021-04-24 06:37
> And I have to kill the process with Ctrl+C

This is not an error. So, you can pop open the Assistant via the [shortcut key binding](https://github.com/Melvin-Abraham/Google-Assistant-Unofficial-Desktop-Client#default-keyboard-shortcut). However, if you are on Wayland windowing system, this might not work in which case you can double-click on the assistant tray icon to open
