### ISSUE TITLE
Unable to view images and videos from the internet

### ISSUE THREAD

**Issue by Himankan** [Melvin-Abraham/Google-Assistant-Unofficial-Desktop-Client#271] opened 2021-04-04 19:26 UTC
When I ask Assistant to show me images or videos of say 'animals', it says "Here are some pictures of animals" and there is nothing below. But it does show my photos from google photos. The same works on my phone really well. Also it's not showing live scores for matches or any media elements.

**Comment by xero-tolerance** [comment] 2021-04-05 12:25
Got the same issue here. Other functions such as "Turn On/Off Lights, create reminder" work properly.

**Comment by walter6469** [comment] 2021-04-05 15:23
Like this 
![Uploading image.png…]()

**Comment by walter6469** [comment] 2021-04-05 15:23
Like this 
![image](https://user-images.githubusercontent.com/70185618/113590968-f6607a00-9650-11eb-96fb-287dcc4efb2d.png)

**Comment by Himankan** [comment] 2021-04-05 17:20
Yes, this issue

**Comment by Melvin-Abraham** [comment] 2021-04-08 12:43
Duplicate of #41

**Comment by Melvin-Abraham** [comment] 2021-04-08 12:43
_Closing as duplicate_

**Closed by Melvin-Abraham** 2021-04-08 12:43 UTC
Labels: duplicate
