### ISSUE TITLE
Crashes on macOS Big Sur

### ISSUE THREAD

**Issue by Bougakov** [Melvin-Abraham/Google-Assistant-Unofficial-Desktop-Client#144] opened 2021-02-16 17:36 UTC
A version downloaded from 'Releases' (a .dmg file) crashes on start. 

The error is:

```
Uncaught Exception:
TypeError: Error processing argument at index 0, conversion failure from 
at Timeout.onAppReady [as _onTimeout] (/Applications/Google Assistant.app/Contents/Resources/app.asar/app.js:192:16)
at listOnTimeout (internal/timers.js:531:17)
at processTimers (internal/timers.js:475:7)
```

**Desktop (please complete the following information):**
  System Version:	macOS 11.2.1 (20D74)
  Kernel Version:	Darwin 20.3.0

**Comment by nullhart** [comment] 2021-02-17 00:26
I had the same issue. Updating GRPC from "grpc": "1.24.4" (which is deprecaited) to "@grpc/grpc-js": "^1.2.7" fixed the issue for me.

**Comment by Melvin-Abraham** [comment] 2021-02-17 04:21
@Bougakov Duplicate of #35.

This is a bug which occurs due to passing a floating-point number to the `setPosition()` function, which is calculated based on your screen size. Thus, the only way to get around it for the time-being is to clone this repo (via `git clone`) and build it yourself (see [How to build](https://github.com/Melvin-Abraham/Google-Assistant-Unofficial-Desktop-Client#how-to-build)) since _**it has been fixed within the source but not released yet.**_

You can learn more about this bug [here](https://github.com/Melvin-Abraham/Google-Assistant-Unofficial-Desktop-Client/issues/35#issuecomment-726725640).

**Comment by Melvin-Abraham** [comment] 2021-02-17 04:24
@nullhart It doesn't seem like it has anything to do with `grpc`. This is an issue related to electron's `setPosition()` function.

**Comment by Melvin-Abraham** [comment] 2021-02-17 04:25
_Closing as duplicate_

**Closed by Melvin-Abraham** 2021-02-17 04:25 UTC
Labels: duplicate
