### ISSUE TITLE
Suggestion - Voice Match and Audio switch

### ISSUE THREAD

**Issue by FreshImmuc** [Melvin-Abraham/Google-Assistant-Unofficial-Desktop-Client#226] opened 2021-03-08 04:22 UTC
Okay, 

1. A useful and really good Feature would be that u can just say: "Okay google" and it launches. Saves time and would be more like the original Assistant...

2. An option to switch the Microphone / Speaker. I have 2 Microphones and i cant use the one that is set as Default. I want that the client uses my 2nd Microphone cause my 1st doesn't work.

**Comment by esau-morais** [comment] 2021-03-08 11:44
Hello, there 👋

> A useful and really good Feature would be that u can just say: "Okay google" and it launches. Saves time and would be more like the original Assistant...

This is already on the roadmap. As soon as possible, it'll be announced.

> An option to switch the Microphone / Speaker. I have 2 Microphones and i cant use the one that is set as Default. I want that the client uses my 2nd Microphone cause my 1st doesn't work.

You can change the input/output device it in the settings

**Comment by FreshImmuc** [comment] 2021-03-08 20:31
I cant change it.. U mean in the Windows settings? cause in the Assistant settings i can't

**Comment by esau-morais** [comment] 2021-03-08 20:58
No, I mean the Google-Assistant settings.

![Mic settings](https://user-images.githubusercontent.com/55207584/110381120-cf099380-8037-11eb-934f-f2f8030474b0.png)

**Comment by FreshImmuc** [comment] 2021-03-08 21:12
https://user-images.githubusercontent.com/65733898/110382527-51577f00-805b-11eb-9edb-714c480917d9.mp4

**Comment by FreshImmuc** [comment] 2021-03-08 21:12
I blurred some areas, thats not a bug or something

**Comment by esau-morais** [comment] 2021-03-08 21:19
The options I've shown are not available to the current released version. What I can recommend to you is to [build the app](https://github.com/Melvin-Abraham/Google-Assistant-Unofficial-Desktop-Client/blob/master/CONTRIBUTING.md#how-to-build) on your local machine in the meantime.

**Comment by FreshImmuc** [comment] 2021-03-10 09:34
Also, the Startup and performance of the Desktop version cloud be improved... I know its hard to make something like this but its faster on my Phone...

**Comment by esau-morais** [comment] 2021-03-10 11:29
It'd be better to reference your comment in a new issue to keep everything organized, closing this one.

**Comment by Melvin-Abraham** [comment] 2021-04-14 17:24
> A useful and really good Feature would be that u can just say: "Okay google" and it launches. Saves time and would be more like the original Assistant

Duplicate of #61

> An option to switch the Microphone / Speaker. I have 2 Microphones and i cant use the one that is set as Default. I want that the client uses my 2nd Microphone cause my 1st doesn't work

Resolved

---

_Closing the issue_

**Closed by Melvin-Abraham** 2021-04-14 17:24 UTC
Labels: ✨ enhancement
